
output_dir: "."
navbar:
  title: "Ashwini Venkatasubramaniam"
  left:
    - text: "Presentations"
      href: presentations.html
    - text: "Teaching"
      href: teaching.html
    - text: "Research"
      href: Research.html
    - text: "Publications"
      href: publications.html
    - text: "Software"
      href: Software.html   
output:
  html_document:
    theme: cosmo
      
