<br />

#### <span style="color:dark blue">**International Conferences**</span>: 

- Joint Statistical Meetings, *Baltimore, United States*, (August 2nd 2017) - Contributed Talk
- International Workshop on Statistical Modelling, *Groningen, Netherlands*, (July 3rd 2017) - Oral Presentation
- European Research in Transportation, hEART 2016, *Delft Institute of Technology,  Netherlands*, (September 2016) - Oral Presentation
- International Conference on Computational Statistics, COMPSTAT, *Oviedo, Spain*, (August 2016) - Contributed Talk
- Machine Learning Summer School, *Max Planck Institute for Intelligent Systems, Tubingen, Germany*, (July 15- 24th 2015) - Poster Presentation, Acceptance Rate - 20%  

#####<span style="color:dark blue">**University of Glasgow**</span>:

- Annual Kelvin Smith Scholar Event, (November 24th 2015) - Poster Presentation
- Annual PhD Talk, School of Statistics, (May 27th 2016 and May 18th 2017) - Oral Presentation
- Annual Kelvin Smith Scholar Event, (November 22nd 2016) - Pecha Kucha Presentation
- Urban Big Data Centre, (September 22nd 2016, May 24th 2016, October 5th 2015) - Oral Presentation